name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write # for checkout and tag
  actions: write # updating envs
  pull-requests: write # for comments
  packages: write # for publish

jobs:
  release-prep:
    runs-on: "ubuntu-latest"
    outputs:
      semver: ${{steps.data.outputs.semver}}
      sha: ${{ steps.data.outputs.short_sha }}
      release_created: ${{ steps.release.outputs.release_created }}
      branch: ${{ steps.branch_names.outputs.current_branch }}
      has_pr: ${{ steps.data.outputs.has_pr }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: google-github-actions/release-please-action@v3
        name: release-please
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: "@swimlane/marketplace"
          include-v-in-tag: false

      - name: Branch Names
        id: branch_names
        uses: tj-actions/branch-names@v5.4

      - name: Load package info
        if: ${{ !needs.release-prep.outputs.release_created }}
        id: pjson
        uses: zoexx/github-action-json-file-properties@release
        with:
          file_path: "package.json"

      - uses: actions/github-script@v6
        id: data
        env:
          MAJOR: ${{steps.release.outputs.major}}
          MINOR: ${{steps.release.outputs.minor}}
          PATCH: ${{steps.release.outputs.patch}}
          PR: ${{steps.release.outputs.pr}}
          RELEASE_CREATED: ${{ steps.release.outputs.release_created }}          
        with:
          script: |
            const script = require('./.github/workflows/scripts/extract-data.js')
            await script({context, core})

      - name: data
        run: |
          echo "semver ${{steps.data.outputs.semver}}"
          echo "sha ${{steps.data.outputs.short_sha}}"
          echo "release_created ${{steps.release.outputs.release_created}}"
          echo "branch ${{steps.branch_names.outputs.current_branch}}"

  build:
    name: build
    runs-on: "ubuntu-latest"
    needs:
      - release-prep
    if: ${{ !needs.release-prep.outputs.release_created }}
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: data
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "${{matrix.image_name}}"
          echo "semver ${{needs.release-prep.outputs.semver}}"
          echo "sha ${{needs.release-prep.outputs.sha}}"
          echo "release_created ${{needs.release-prep.outputs.release_created}}"
          echo "branch ${{needs.release-prep.outputs.branch}}"

  # publish:
  #   runs-on: "ubuntu-latest"
  #   if: ${{ needs.release-prep.outputs.release_created }}
  #   needs:
  #     - release-prep
  #   strategy:
  #     matrix:
  #       app: ["api", "ui-hub"]
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0

  #     - name: data
  #       env:
  #         GITHUB_CONTEXT: ${{ toJSON(github) }}
  #       run: |
  #         echo "$GITHUB_CONTEXT"
  #         echo "${{matrix.image_name}}"
  #         echo "semver ${{needs.release-prep.outputs.semver}}"
  #         echo "sha ${{needs.release-prep.outputs.sha}}"
  #         echo "release_created ${{needs.release-prep.outputs.release_created}}"
  #         echo "branch ${{needs.release-prep.outputs.branch}}"
